services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"  # Map host port to container port 80
    environment:
      - API_URL=${API_URL}     # Use backend service name
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"            # Map backend container to host port 8080
    env_file: 
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: postgres -c listen_addresses='*'

  redis:
    image: redis:6
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
